os: linux
dist: trusty
jdk: openjdk8
script:
- "./gradlew build"
- "./gradlew jacocoTestReport"
services:
- docker
after_success:
- bash <(curl -s https://codecov.io/bash)
- docker build -t kotlin-cannon .
- docker login -u $DOCKER_USERNAME  -p $DOCKER_PASSWORD
- docker tag $IMAGE_NAME:latest $DOCKER_USERNAME/$IMAGE_NAME:latest
- docker push $DOCKER_USERNAME/$IMAGE_NAME:latest

# env:
#   global:
#     secure: DOCKER_USERNAME
#     secure: DOCKER_PASSWORD
#     secure: IMAGE_NAME
env:
  matrix:
  - secure: m11nyDjP98cETY2yGR7L7j5WGz+y/doruMPH1Cd7rJ5aE2HIngRR2ID0+0WObj11TcvA9V8PIHBN6cqaIBUtmbgqTVK42+LTXrLAqfRoGOMcV/CnHpaKbYaP7E/ns1u/hXMjTww2ber9Zg917ZAqkzCG5HFr7MtM84EcPsJ6X0gaTZtg5KQI98RUMb+fJ60NbxwtFuhgUobjoLZR5aTFcwE0ABjsoxEpEqar+WGhaQaZu2faNI8+buqnF80RGd7VKSM3NZUQQGILXayMk3CRIPeFtk4uUzWNo9tQHCegsrDvwLrF6roG38Wo39BtPYWIgFecWTmGZVpagSemtb/+dFCCjP1DS1pFKB7EEbCSSbZpeRN59YHaSh9efz4RyOQiDHz1D5mkKC4IyjwmYprltLwVCgp5GNZO+sKJ4leD69iRXwnuhIPWUOzwOGROZ9ucPqdjqB8Bd4fL1sTqftPEaD8gylzRziMVS0kZjrwPz4zSjXZ8S+kDnMt16aoitW4MyLhACxCav+FPLmNixLISDkZ3mnUs1gS+Oyirbm2A6t1d96lLKiz/urKR+ibxRyv41GeM3oB3PzZn6nSgufxHSg1hfPV/0m4LzhHWUs58LiRbdXR4iensOqQcQWp4Cp1L14xcIAMBuyf11BfWPMyMwxBud/lofMf5cnkt7AX5Qa4=
  - secure: TBviHn/ut3XM6JO/vj103Cb1mrN4A9Qds324jZ2CEJwFhJQCnmStdMV9IWg4QdFfSNYr8vf6+az7n7IF6ebcVeOpLP0f8UODdnnMF8pN1yyd/WVjlqnvS4Z3Z1HMvFdCzMV4I8nCSugah1mpowgLM+8a8hBGVzgGEi1SAEEqCXIoGeUxyLE3gBR9yDn0GKX+d1Ct1s33d64sGXZIeXAwRuSHu+CUHnMaKi1eAN1jXN6lTmXAeCakqEEGlIkEhSss+9WIxQjpoEenaL2fNcEie9wtMrjAB34+eP0Tepxq/5Yh0m0QD3+NFcRfi04fwxisvhT1zTU100N9Q+qbw1T10mv8XMD40qYOGEkVExTDCNXBausQc0f9fdp9cyHrbnM8CECYAwtv6vAj1h6WBdhs61MxYtI6bInI2dwgk5lorvV0oxJNctK7W6B6LSCpBOAhroTE8nW4IqPi5X4MK81Yx30OB4tMIcYR7XrtcEzGVQ8t1gcleLOOdaxyxVJ2P+MKAxokKS3pyFpxyYCwHpfgXDPKer+md+n0mFKrkn36DIawXGQgSjFQHZFeD2J2ihl0eMFtOxyq4dI/Sod4Hnl9xzh3HtNhIPhJtN9HPe9L3JwLlY2z1yFZPA+LfcXSHzFraB58YhPxCxCig+tKWnk3M5upzBjffMCnSyVUvWO5C18=
  - secure: fohQJcDChpjseavjtOPHU7yZ0A7AAf/D6ZOeK0cW8IiKOQ9k8dWjUEdDcl+QYeNkOc0rLbAj2DhtOClJd92Aag8xPux2NCRyuby8wnQkXAcelCNxVdcOHJXeGuv1uUzgRdMJn1DD8iMlaw2RpMWhKRbdbJ6M9ZJGUYi/egpPgS6y6H3Acv1YfZbFHcl1hCIToLZyLWxeBmTmMkSkVqSazoAoXUbOokNTR6WpidUOxWG1V0mblESeZZTKIdotaP+xFI3iYQDwhHFE1it7cUo2ameldScoA4qVF23zkSy/fhhSkp8LbfG+Xxr6ZQHTlzp50noaFCGyeD+VAZsEFvhefbRp3MyUP3t5x3orwRkJyr1qLT1P4jTDEk74hOdflUeC+wFiruz1Y2cVmknmfvy6RgkPCjGX6gk01czQrcDoDzFugxpHgwiXeE+tO54WCdVjv61i/RLuf/wavYo5EoqckWUuJUJRAiU6EAmUrulYagKv6q7xV1oY6ciBvyCwayrhOmeRExbPr1Qzsb+Rm3PwGcAXjTdebjOpcSTdVujVZqjx6EVx8uFGO3QEVyWlyxyJrKreo9hmwaQ4C8F6Id1ImiAJQwFflL6mKJZKrTqmx7us+W96ZUISMY9CxvJbBj7GcmZlzqHhq1V1JC+RA0utEHAgFaKUYjPh7iH2ZU+IPY8=
