version: '2.1'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7.27
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cannon
    volumes:
      - cannon-mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

  cannon:
    container_name: cannon
    image: cannon:latest
    ports:
      - "8080:8080"
    links:
      - mysql
    depends_on:
      - mysql

volumes:
  cannon-mysql-data:
    driver: local
